import { derbyVoice, seedFrom } from "./voice";
import type { DerbyHype, HeadToHead, LeagueRow } from "./types";

/**
 * The write-up above each head-to-head countdown.
 *
 * Everything factual comes from real data — the head-to-head record and
 * previous meetings from ESPN, positions from the live table, scorers from the
 * stat leaders — and the sentences carrying it are generated by the grammar in
 * voice.ts, seeded on the fixture so a given derby always reads the same way.
 *
 * Only the rivalry notes below are written by hand. They are history rather
 * than anything that dates, and they are the one part that should not be
 * generated: a grammar would happily invent a reason these two dislike each
 * other, and that is not the kind of thing to make up.
 */

type Rivalry = { name: string; note: string };

/** Keyed on the two team ids sorted ascending, so order of the fixture is irrelevant. */
const RIVALRIES: Record<string, Rivalry> = {
  "103:110": {
    name: "Derby della Madonnina",
    note: "Two clubs, one stadium. Inter exist because a faction walked out of Milan in 1908, and San Siro has been split down the middle ever since.",
  },
  "110:111": {
    name: "Derby d'Italia",
    note: "Named by Gianni Brera for a reason: for most of the last century the title has gone through one of these two. There is no love lost and never has been.",
  },
  "104:112": {
    name: "Derby della Capitale",
    note: "Rome divided. One city, two clubs, and a fixture that has never been merely a football match.",
  },
  "104:114": {
    name: "Derby del Sole",
    note: "The derby of the sun — the south's two biggest clubs, and a rivalry that runs far hotter than the geography suggests.",
  },
  "103:111": {
    name: "The old rivalry",
    note: "Between them these two have more Italian titles and more European Cups than anyone else in the country. It has decided a lot of seasons.",
  },
  "110:114": {
    name: "Scudetto weather",
    note: "The north's establishment against the south's champions. Recent title races have come down to this pairing more than once.",
  },
};

function rivalryFor(a: number, b: number): Rivalry | null {
  const key = [a, b].sort((x, y) => x - y).join(":");
  return RIVALRIES[key] ?? null;
}

function ordinal(n: number): string {
  const rest = n % 100;
  if (rest >= 11 && rest <= 13) return `${n}th`;
  return `${n}${["th", "st", "nd", "rd"][n % 10] ?? "th"}`;
}

function monthYear(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("en-GB", { month: "long", year: "numeric" });
}

export function buildHype(input: {
  fixtureId: number;
  homeTeamId: number;
  homeName: string;
  homeOwner: string | null;
  awayTeamId: number;
  awayName: string;
  awayOwner: string | null;
  competitionName: string;
  headToHead: HeadToHead | null;
  homeRow: LeagueRow | null;
  awayRow: LeagueRow | null;
  homeScorer: { name: string; goals: number } | null;
  awayScorer: { name: string; goals: number } | null;
}): DerbyHype {
  const rivalry = rivalryFor(input.homeTeamId, input.awayTeamId);
  const facts: { label: string; value: string }[] = [];
  const sentences: string[] = [];

  const voice = derbyVoice(seedFrom(`${input.fixtureId}:${input.homeTeamId}`));
  // Everything but Serie A reads better with the article: "in the Coppa Italia",
  // but "in Serie A".
  const comp = /^Serie A$/.test(input.competitionName)
    ? input.competitionName
    : `the ${input.competitionName}`;
  const clubs = { aClub: input.homeName, bClub: input.awayName, comp };
  const push = (text: string) => {
    if (text) sentences.push(text);
  };

  /* ------------------------------------------------------------- the stakes */

  if (input.homeOwner && input.awayOwner) {
    push(voice.say("stakesOwned", { ...clubs, a: input.homeOwner, b: input.awayOwner }));
  } else {
    push(voice.say("stakesPlain", clubs));
  }

  /* ---------------------------------------------------------- league context */

  const started = (row: LeagueRow | null) => row && row.played > 0;
  if (started(input.homeRow) && started(input.awayRow)) {
    const h = input.homeRow as LeagueRow;
    const a = input.awayRow as LeagueRow;
    push(
      voice.say("table", {
        aClub: h.name,
        aRank: ordinal(h.rank),
        aPts: h.points,
        aUnit: h.points === 1 ? "point" : "points",
        bClub: a.name,
        bRank: ordinal(a.rank),
        bPts: a.points,
      }),
    );
    facts.push({
      label: "In the table",
      value: `${ordinal(h.rank)} v ${ordinal(a.rank)}`,
    });
  } else {
    push(voice.say("tableEarly"));
  }

  /* -------------------------------------------------------------- the record */

  if (input.headToHead?.summary) {
    facts.push({ label: "Head-to-head", value: input.headToHead.summary });
  }

  const last = input.headToHead?.meetings?.[0];
  if (last) {
    const drawn = last.homeScore === last.awayScore;
    const winner = last.homeScore > last.awayScore ? last.homeName : last.awayName;
    push(
      drawn
        ? voice.say("lastDrawn", {
            score: `${last.homeScore}-${last.awayScore}`,
            when: monthYear(last.date),
          })
        : voice.say("lastWon", {
            winner,
            score: `${Math.max(last.homeScore, last.awayScore)}-${Math.min(
              last.homeScore,
              last.awayScore,
            )}`,
            when: monthYear(last.date),
          }),
    );
    facts.push({
      label: "Last meeting",
      value: `${last.homeName} ${last.homeScore}-${last.awayScore} ${last.awayName}`,
    });
  }

  /* ---------------------------------------------------------- who to watch */

  const watch: string[] = [];
  if (input.homeScorer) watch.push(`${input.homeScorer.name} (${input.homeScorer.goals})`);
  if (input.awayScorer) watch.push(`${input.awayScorer.name} (${input.awayScorer.goals})`);
  if (watch.length) {
    facts.push({ label: "Leading scorers", value: watch.join(" · ") });
    push(
      watch.length === 2
        ? voice.say("watchTwo", {
            a: input.homeScorer?.name ?? "",
            b: input.awayScorer?.name ?? "",
          })
        : voice.say("watchOne", { a: watch[0] }),
    );
  }

  return {
    rivalry: rivalry?.name ?? null,
    rivalryNote: rivalry?.note ?? null,
    blurb: sentences.join(" "),
    facts,
  };
}
